theme: jekyll-theme-cayman
show_downloads: false
title: [Springer Book: Formal Methods for Software Engineering]
description: [Website accompanying the book Formal Methods for Software Engineering published by Springer in 2022]